version: '2.4'
services:
  templateappchangeme:
    build: ./docker
    ports:
      - "127.0.0.1:9001:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
    mem_limit: 300M
    restart: unless-stopped